2018-03-30 13:18:38.778 EDT [5089] LOG:  listening on IPv6 address "::1", port 5432
2018-03-30 13:18:38.778 EDT [5089] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-03-30 13:18:38.779 EDT [5089] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2018-03-30 13:18:38.805 EDT [5090] LOG:  database system was shut down at 2018-03-30 13:05:06 EDT
2018-03-30 13:18:38.814 EDT [5089] LOG:  database system is ready to accept connections
2018-03-30 13:21:26.591 EDT [5195] FATAL:  lock file "postmaster.pid" already exists
2018-03-30 13:21:26.591 EDT [5195] HINT:  Is another postmaster (PID 5089) running in data directory "/Users/ilyas/HC/pg-holo"?
2018-03-30 13:21:26.698 EDT [5197] ERROR:  database "holo" already exists
2018-03-30 13:21:26.698 EDT [5197] STATEMENT:  CREATE database holo;
2018-03-30 13:21:26.698 EDT [5197] ERROR:  role "holocleanuser" already exists
2018-03-30 13:21:26.698 EDT [5197] STATEMENT:  CREATE user holocleanuser;
2018-04-01 12:56:49.277 EDT [5089] LOG:  received smart shutdown request
2018-04-01 12:56:49.279 EDT [5089] LOG:  worker process: logical replication launcher (PID 5096) exited with exit code 1
2018-04-01 12:56:49.279 EDT [5091] LOG:  shutting down
2018-04-01 12:56:50.026 EDT [5089] LOG:  database system is shut down
2018-04-01 15:18:31.027 EDT [1198] LOG:  listening on IPv6 address "::1", port 5432
2018-04-01 15:18:31.027 EDT [1198] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-04-01 15:18:31.028 EDT [1198] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2018-04-01 15:18:31.053 EDT [1199] LOG:  database system was shut down at 2018-04-01 12:56:49 EDT
2018-04-01 15:18:31.066 EDT [1198] LOG:  database system is ready to accept connections
2018-04-01 15:22:09.473 EDT [1358] LOG:  could not receive data from client: Connection reset by peer
2018-04-01 15:22:09.473 EDT [1358] LOG:  unexpected EOF on client connection with an open transaction
2018-04-02 20:46:43.925 EDT [56194] ERROR:  relation "inferred_values_229954674673" does not exist at character 30
2018-04-02 20:46:43.925 EDT [56194] STATEMENT:  SELECT * FROM (Select * from Inferred_values_229954674673) as tablename WHERE 1=0
2018-04-02 21:25:22.429 EDT [57192] ERROR:  relation "inferred_values_578969636964" does not exist at character 30
2018-04-02 21:25:22.429 EDT [57192] STATEMENT:  SELECT * FROM (Select * from Inferred_values_578969636964) as tablename WHERE 1=0
2018-04-02 21:30:16.730 EDT [57919] ERROR:  relation "inferred_values_229303872526" does not exist at character 30
2018-04-02 21:30:16.730 EDT [57919] STATEMENT:  SELECT * FROM (Select * from Inferred_values_229303872526) as tablename WHERE 1=0
2018-04-02 21:48:54.492 EDT [59889] ERROR:  relation "inferred_values_407844486799" does not exist at character 30
2018-04-02 21:48:54.492 EDT [59889] STATEMENT:  SELECT * FROM (Select * from Inferred_values_407844486799) as tablename WHERE 1=0
2018-04-02 21:57:27.574 EDT [60662] ERROR:  relation "inferred_values_048106836853" does not exist at character 30
2018-04-02 21:57:27.574 EDT [60662] STATEMENT:  SELECT * FROM (Select * from Inferred_values_048106836853) as tablename WHERE 1=0
2018-04-02 22:03:32.595 EDT [61361] ERROR:  relation "inferred_values_027814720916" does not exist at character 30
2018-04-02 22:03:32.595 EDT [61361] STATEMENT:  SELECT * FROM (Select * from Inferred_values_027814720916) as tablename WHERE 1=0
2018-04-02 23:45:47.059 EDT [69287] LOG:  unexpected EOF on client connection with an open transaction
